# Generated by Django 4.1 on 2022-09-01 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=25, null=True)),
                ('address', models.TextField()),
                ('occupation', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.CharField(blank=True, choices=[('Bachelor of Technology', 'Bachelor of Technology'), ('Bachelor of Engineering', 'Bachelor of Engineering'), ('Master of Technology', 'Master of Technology'), ('Master of Engineering', 'Master of Engineering'), ('Master of Business Administration', 'Master of Business Administration')], max_length=50, null=True)),
                ('branch', models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Electronics and Communications', 'Electronics and Communications'), ('Electrical and Electronics', 'Electrical and Electronics'), ('Information Technology', 'Information Technology'), ('Chemical', 'Chemical'), ('Mechanical', 'Mechanical'), ('Mechatronics', 'Mechatronics'), ('Civil', 'Civil'), ('Humanities and Science', 'Humanities and Science'), ('Management', 'Management')], max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('year_of_passing', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
